### ISSUE TITLE
5.0.10 Apps, push menu not available

### ISSUE THREAD

**Issue by SiberianCMS** [Xtraball/Siberian#839]
Since 5.x and for sure 5.0.10 the push menu in the account settings is blank

![6_push](https://github.com/Xtraball/Siberian/assets/7977082/773e40cb-3ec7-4270-8f24-bea2f2a08490)

**Comment by SiberianCMS** [comment]
Log report on crash

```
FATAL EXCEPTION: main
                                                                                                    Process: com.xtraball.androidappoff, PID: 25701
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.isShown()' on a null object reference
                                                                                                    	at nl.xservices.plugins.Toast$1$1.onTouch(Toast.java:149)
                                                                                                    	at android.view.View.dispatchTouchEvent(View.java:14568)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3167)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2809)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3173)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:697)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1978)
                                                                                                    	at android.app.Activity.dispatchTouchEvent(Activity.java:4195)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:655)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:14844)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6635)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6417)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5891)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5948)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5914)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6079)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5922)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6136)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5895)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5948)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5914)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5922)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5895)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8949)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8889)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8846)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9081)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:161)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7924)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```
